global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using ShoppingApp.Core.DataAccess;
global using ShoppingApp.Core.Entities;
global using ShoppingApp.Core.DataAccess.Ef;
global using ShoppingApp.Infrastructure.Abstract;